services:
  mongo.db.catalog:
    restart: always
    image: mongo:8.0-rc
    container_name: mongo.db.catalog.container
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
    ports:
    # 27017 bu port mongo db default portudur.Normalde 27017 docker içinde kaldýrma portudu, normalde mongo nun default portu 27017 dir, container içinde bunu bu porttan dýþarýya açýyoruz.27030 da by port dýþarýdan eriþim için kullanýlacak porttur.Yani dýþarýya açýlan port 27030 olacak.
      - "27030:27017" 
    volumes:
      - mongo.db.catalog.volume:/data/db
  mongo.db.catalog.ui:
    image: mongo-express:1.0.2-20-alpine3.19
    container_name: mongo.db.catalog.ui
    ports:
      - 27032:8081
    environment:
# mongo.db.catalog.container içindeki mongo db ye eriþim için kullanýlacak url, bu url ile mongo db ye eriþim saðlanacak. domain adý sayýlýr.
      ME_CONFIG_MONGODB_URL: mongodb://${MONGO_USERNAME}:${MONGO_PASSWORD}@mongo.db.catalog:27017/
      # Uý a girerken kullanýcý adý ve þifre istemez
      ME_CONFIG_BASICAUTH: false 
volumes:
  mongo.db.catalog.volume:
  
     # mongo.db.catalog farkýndaysan isim olarak bunu kllandýk hep ana olarak, domain aslýnda, docker bu domaini tanýyacak ve bu domain üzerinden eriþim saðlayacak.