@baseAddress = http://localhost:5132

GET {{baseAddress}}/api/categories
Accept: application/json
###

Post {{baseAddress}}/api/categories
Accept: application/json
Content-Type: application/json
{
  "name": "Category 1",
  "description": "Category 1 Description"
}
###
