@baseAddress = http://localhost:5132

GET {{baseAddress}}/api/categories
Accept: application/json
###

Post {{baseAddress}}/api/categories
Accept: application/json
Content-Type: application/json
{
  "name": "Category 1",
  "description": "Category 1 Description"
}
###

GET {{baseAddress}}/api/categories/08dd041d-5835-2e46-b025-aa5780660000
Accept: application/json
